import React, { useState, useRef, useEffect } from 'react';
import Header from './Header';
import ContentPreview from './ContentPreview';
import contentService from '../services/contentService';
import type { Content } from '../services/contentService';

interface ContentItem {
  id: string;
  name: string;
  type: 'document' | 'video' | 'audio' | 'image' | 'link';
  size: string;
  uploadDate: string;
  linkedPaywalls: number;
  thumbnail: string;
  folderId: string;
  tags: string[];
  description?: string;
  isProtected: boolean;
  permissions: string[];
  revenue?: number; // Revenue generated by this content
  earnings?: number; // Earnings from this content (if different from revenue)
}

interface UploadProgress {
  id: string;
  fileName: string;
  progress: number;
  status: 'uploading' | 'completed' | 'failed';
  type: 'document' | 'video' | 'audio' | 'image' | 'link';
}

interface Folder {
  id: string;
  name: string;
  parentId?: string; // For subfolders
  items: ContentItem[];
  createdAt: string;
  updatedAt: string;
}

interface Tag {
  id: string;
  name: string;
  color: string;
}

const ContentLibrary: React.FC = () => {
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');
  const [searchTerm, setSearchTerm] = useState('');
  const [filterType, setFilterType] = useState<string>('all');
  const [folders, setFolders] = useState<Folder[]>([]);
  const [tags, setTags] = useState<Tag[]>([]);
  const [activeFolder, setActiveFolder] = useState<string>('');
  const [isDragging, setIsDragging] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [previewItem, setPreviewItem] = useState<ContentItem | null>(null);
  const [uploadProgress, setUploadProgress] = useState<UploadProgress[]>([]);
  const [newFolderName, setNewFolderName] = useState('');
  const [showNewFolderInput, setShowNewFolderInput] = useState(false);
  const [editingFolderId, setEditingFolderId] = useState<string | null>(null);
  const [editingFolderName, setEditingFolderName] = useState('');
  const [selectedItems, setSelectedItems] = useState<string[]>([]);
  const [showBulkActions, setShowBulkActions] = useState(false);
  const [storageUsage, setStorageUsage] = useState({ used: 0, limit: 10, percentage: 0 });
  const [newTagName, setNewTagName] = useState('');
  const [showAddTagInput, setShowAddTagInput] = useState(false);
  const [editingItemTags, setEditingItemTags] = useState<{[key: string]: string[]}>({});
  const [showItemTagsInput, setShowItemTagsInput] = useState<string | null>(null);
  const [showUploadModal, setShowUploadModal] = useState(false);
  const [uploadFiles, setUploadFiles] = useState<File[]>([]);
  const [uploadMetadata, setUploadMetadata] = useState<{[key: string]: {name: string, tags: string[], folderId: string}}>({});
  const [selectionMode, setSelectionMode] = useState(false);
  const [selectedContent, setSelectedContent] = useState<string[]>([]);
  const [onSelectCallback, setOnSelectCallback] = useState<((selected: ContentItem[]) => void) | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const newFolderInputRef = useRef<HTMLInputElement>(null);

  // Load content data from the backend
  useEffect(() => {
    const loadContentData = async () => {
      try {
        // Fetch content from the backend
        const response = await contentService.getAllContent();
        const contentItems = response.data || [];
        
        // Group content into folders (simulating folder structure)
        const folderMap: { [key: string]: Folder } = {};
        
        // Create a default "General" folder if it doesn't exist
        if (!folderMap['1']) {
          folderMap['1'] = {
            id: '1',
            name: 'General',
            items: [],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
          };
        }

        // Process each content item
        contentItems.forEach(item => {
          // Create folder structure based on content data
          // For now, we'll put everything in the General folder
          const folder = folderMap['1'];
          if (folder) {
            folder.items.push({
              id: item.id?.toString() || `content-${Date.now()}`,
              name: item.title || 'Untitled',
              type: (item.type as any) || 'document',
              size: item.size || 'N/A',
              uploadDate: item.createdAt ? new Date(item.createdAt).toISOString().split('T')[0] : new Date().toISOString().split('T')[0],
              linkedPaywalls: 0, // This would need to come from backend
              thumbnail: (item.type as any) || 'document',
              folderId: '1',
              tags: item.tags || [], 
              description: item.description,
              isProtected: item.isProtected || false,
              permissions: ['read'], // Permissions would come from backend
              revenue: 0 // Revenue would come from backend
            });
          }
        });

        const folderList = Object.values(folderMap);
        setFolders(folderList);
        
        if (folderList.length > 0) {
          setActiveFolder(folderList[0].id);
        }
        
        // Set up default tags
        setTags([
          { id: '1', name: 'marketing', color: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300' },
          { id: '2', name: 'product', color: 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300' },
          { id: '3', name: 'tutorial', color: 'bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300' },
          { id: '4', name: 'education', color: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300' },
          { id: '5', name: 'design', color: 'bg-pink-100 text-pink-800 dark:bg-pink-900/30 dark:text-pink-300' },
          { id: '6', name: 'website', color: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-300' }
        ]);
      } catch (error) {
        console.error('Error loading content data:', error);
        // Initialize with empty data if API call fails
        setFolders([{
          id: '1',
          name: 'General',
          items: [],
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString()
        }]);
        setActiveFolder('1');
        setTags([
          { id: '1', name: 'marketing', color: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300' },
          { id: '2', name: 'product', color: 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300' },
          { id: '3', name: 'tutorial', color: 'bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300' },
          { id: '4', name: 'education', color: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300' },
          { id: '5', name: 'design', color: 'bg-pink-100 text-pink-800 dark:bg-pink-900/30 dark:text-pink-300' },
          { id: '6', name: 'website', color: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-300' }
        ]);
      }
    };

    loadContentData();
  }, []);

  const allItems = folders.flatMap(folder => 
    folder.items.map(item => ({ ...item, folderId: folder.id }))
  );

  const filteredItems = allItems.filter(item => {
    const matchesSearch = item.name.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesType = filterType === 'all' || item.type === filterType;
    return matchesSearch && matchesType;
  });

  const handleUploadClick = () => {
    fileInputRef.current?.click();
  };

  // Folder management functions
  const createNewFolder = () => {
    if (newFolderName.trim() === '') return;
    
    const newFolder: Folder = {
      id: `folder-${Date.now()}`,
      name: newFolderName.trim(),
      items: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };
    
    setFolders(prev => [...prev, newFolder]);
    setNewFolderName('');
    setShowNewFolderInput(false);
  };

  const startEditingFolder = (folderId: string, folderName: string) => {
    setEditingFolderId(folderId);
    setEditingFolderName(folderName);
  };

  const saveFolderEdit = () => {
    if (editingFolderId && editingFolderName.trim() !== '') {
      setFolders(prev => 
        prev.map(folder => 
          folder.id === editingFolderId 
            ? { ...folder, name: editingFolderName.trim() } 
            : folder
        )
      );
      setEditingFolderId(null);
      setEditingFolderName('');
    }
  };

  const deleteFolder = (folderId: string) => {
    if (window.confirm('Are you sure you want to delete this folder? All content inside will be moved to General folder.')) {
      // Move items to General folder before deleting
      setFolders(prev => {
        const folderToDelete = prev.find(f => f.id === folderId);
        if (!folderToDelete) return prev;
        
        return prev
          .map(folder => {
            if (folder.id === '1') { // General folder
              return {
                ...folder,
                items: [...folder.items, ...folderToDelete.items],
                updatedAt: new Date().toISOString()
              };
            }
            return folder;
          })
          .filter(folder => folder.id !== folderId);
      });
      
      // If we're deleting the active folder, switch to General
      if (activeFolder === folderId) {
        setActiveFolder('1');
      }
    }
  };

  // Item selection functions
  const toggleItemSelection = (itemId: string) => {
    setSelectedItems(prev => {
      if (prev.includes(itemId)) {
        return prev.filter(id => id !== itemId);
      } else {
        return [...prev, itemId];
      }
    });
  };

  const selectAllItems = () => {
    const currentFolder = folders.find(f => f.id === activeFolder);
    if (currentFolder) {
      setSelectedItems(currentFolder.items.map(item => item.id));
    }
  };

  const deselectAllItems = () => {
    setSelectedItems([]);
  };

  // Effect to show/hide bulk actions
  useEffect(() => {
    setShowBulkActions(selectedItems.length > 0);
  }, [selectedItems]);

  // Bulk actions
  const deleteSelectedItems = () => {
    if (window.confirm(`Are you sure you want to delete ${selectedItems.length} item(s)?`)) {
      setFolders(prev => 
        prev.map(folder => {
          if (folder.id === activeFolder) {
            return {
              ...folder,
              items: folder.items.filter(item => !selectedItems.includes(item.id))
            };
          }
          return folder;
        })
      );
      setSelectedItems([]);
    }
  };

  const moveSelectedItems = (targetFolderId: string) => {
    if (targetFolderId === activeFolder) return;
    
    setFolders(prev => {
      const updatedFolders = [...prev];
      const sourceFolderIndex = updatedFolders.findIndex(f => f.id === activeFolder);
      const targetFolderIndex = updatedFolders.findIndex(f => f.id === targetFolderId);
      
      if (sourceFolderIndex !== -1 && targetFolderIndex !== -1) {
        const selectedItemsData = updatedFolders[sourceFolderIndex].items.filter(item => 
          selectedItems.includes(item.id)
        );
        
        // Remove from source folder
        updatedFolders[sourceFolderIndex] = {
          ...updatedFolders[sourceFolderIndex],
          items: updatedFolders[sourceFolderIndex].items.filter(item => 
            !selectedItems.includes(item.id)
          ),
          updatedAt: new Date().toISOString()
        };
        
        // Add to target folder
        updatedFolders[targetFolderIndex] = {
          ...updatedFolders[targetFolderIndex],
          items: [...updatedFolders[targetFolderIndex].items, ...selectedItemsData],
          updatedAt: new Date().toISOString()
        };
      }
      
      return updatedFolders;
    });
    
    setSelectedItems([]);
  };



  const getFileType = (fileType: string): 'document' | 'video' | 'audio' | 'image' | 'link' => {
    if (fileType.includes('image')) return 'image';
    if (fileType.includes('video')) return 'video';
    if (fileType.includes('audio')) return 'audio';
    if (fileType.includes('pdf') || fileType.includes('document')) return 'document';
    return 'document'; // default
  };

  const formatFileSize = (bytes: number): string => {
    if (bytes < 1024) return bytes + ' bytes';
    else if (bytes < 1048576) return (bytes / 1024).toFixed(1) + ' KB';
    else return (bytes / 1048576).toFixed(1) + ' MB';
  };

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    handleFileSelect(e);
  };

  const handleDragOver = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = () => {
    setIsDragging(false);
  };

  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);
    const files = e.dataTransfer.files;
    if (files.length > 0) {
      // Convert FileList to File[] and trigger the modal
      const filesArray = Array.from(files);
      setUploadFiles(filesArray);
      
      // Initialize metadata for each file
      const initialMetadata: {[key: string]: {name: string, tags: string[], folderId: string}} = {};
      filesArray.forEach(file => {
        initialMetadata[file.name] = {
          name: file.name,
          tags: [],
          folderId: activeFolder // Default to current active folder
        };
      });
      setUploadMetadata(initialMetadata);
      setShowUploadModal(true);
    }
  };

  const handlePreview = (item: ContentItem) => {
    setPreviewItem(item);
    setShowPreview(true);
  };

  // Get all items in the current folder
  const getCurrentFolderItems = () => {
    const currentFolder = folders.find(f => f.id === activeFolder);
    return currentFolder ? currentFolder.items : [];
  };

  // Filter items based on search and type
  const getFilteredItems = () => {
    const items = getCurrentFolderItems();
    return items.filter(item => {
      const matchesSearch = item.name.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesType = filterType === 'all' || item.type === filterType;
      return matchesSearch && matchesType;
    });
  };

  // Get icon for folder
  const getFolderIcon = () => {
    return (
      <svg className="h-5 w-5 text-indigo-600 dark:text-indigo-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
      </svg>
    );
  };

  // Get icon based on file type
  const getFileIcon = (type: string) => {
    switch (type) {
      case 'document':
        return (
          <svg className="h-10 w-10 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
        );
      case 'video':
        return (
          <svg className="h-10 w-10 text-blue-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" />
          </svg>
        );
      case 'audio':
        return (
          <svg className="h-10 w-10 text-purple-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M9 19V6l12-3v13M9 19c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zm12-3c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zM9 10l12-3" />
          </svg>
        );
      case 'image':
        return (
          <svg className="h-10 w-10 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
          </svg>
        );
      default:
        return (
          <svg className="h-10 w-10 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
        );
    }
  };

  // Function to delete an item
  const deleteItem = (itemId: string) => {
    if (window.confirm('Are you sure you want to delete this content?')) {
      setFolders(prev => 
        prev.map(folder => ({
          ...folder,
          items: folder.items.filter(item => item.id !== itemId)
        }))
      );
    }
  };

  // Function to edit an item
  const [editingItem, setEditingItem] = useState<ContentItem | null>(null);
  const [editedItemName, setEditedItemName] = useState('');

  const startEditingItem = (item: ContentItem) => {
    setEditingItem(item);
    setEditedItemName(item.name);
  };

  const saveItemEdit = () => {
    if (editingItem) {
      setFolders(prev => 
        prev.map(folder => ({
          ...folder,
          items: folder.items.map(item => 
            item.id === editingItem.id 
              ? { ...item, name: editedItemName } 
              : item
          )
        }))
      );
      setEditingItem(null);
      setEditedItemName('');
    }
  };

  const cancelItemEdit = () => {
    setEditingItem(null);
    setEditedItemName('');
  };

  // Function to add a new global tag
  const addNewTag = () => {
    if (newTagName.trim() === '') return;
    
    // Generate a random color class for the new tag
    const colors = [
      'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300',
      'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300',
      'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300',
      'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300',
      'bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300',
      'bg-pink-100 text-pink-800 dark:bg-pink-900/30 dark:text-pink-300',
      'bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-300',
      'bg-gray-100 text-gray-800 dark:bg-gray-900/30 dark:text-gray-300',
      'bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-300',
      'bg-teal-100 text-teal-800 dark:bg-teal-900/30 dark:text-teal-300'
    ];
    
    const randomColor = colors[Math.floor(Math.random() * colors.length)];
    
    const newTag: Tag = {
      id: `tag-${Date.now()}`,
      name: newTagName.trim(),
      color: randomColor
    };
    
    setTags(prev => [...prev, newTag]);
    setNewTagName('');
    setShowAddTagInput(false);
  };

  // Function to add a tag to a content item
  const addItemTag = (itemId: string) => {
    if (!showItemTagsInput || !editingItemTags[itemId]?.trim()) return;
    
    setFolders(prev => 
      prev.map(folder => ({
        ...folder,
        items: folder.items.map(item => {
          if (item.id === itemId) {
            // Only add if tag doesn't already exist
            if (!item.tags.includes(editingItemTags[itemId])) {
              return {
                ...item,
                tags: [...item.tags, editingItemTags[itemId]]
              };
            }
          }
          return item;
        })
      }))
    );
    
    // Clear the input
    setEditingItemTags(prev => ({
      ...prev,
      [itemId]: ''
    }));
  };

  // Function to remove a tag from a content item
  const removeItemTag = (itemId: string, tagToRemove: string) => {
    setFolders(prev => 
      prev.map(folder => ({
        ...folder,
        items: folder.items.map(item => {
          if (item.id === itemId) {
            return {
              ...item,
              tags: item.tags.filter(tag => tag !== tagToRemove)
            };
          }
          return item;
        })
      }))
    );
  };

  // Function to handle file selection for upload modal
  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files && files.length > 0) {
      setUploadFiles(Array.from(files));
      
      // Initialize metadata for each file
      const initialMetadata: {[key: string]: {name: string, tags: string[], folderId: string}} = {};
      Array.from(files).forEach(file => {
        initialMetadata[file.name] = {
          name: file.name,
          tags: [],
          folderId: activeFolder // Default to current active folder
        };
      });
      setUploadMetadata(initialMetadata);
      setShowUploadModal(true);
    }
  };

  // Function to update metadata for a file
  const updateFileMetadata = (fileName: string, field: 'name' | 'tags' | 'folderId', value: any) => {
    setUploadMetadata(prev => ({
      ...prev,
      [fileName]: {
        ...prev[fileName],
        [field]: value
      }
    }));
  };

  // Function to add a tag to a file in upload modal
  const addFileTag = (fileName: string, tag: string) => {
    if (!tag.trim()) return;
    
    setUploadMetadata(prev => {
      const currentTags = prev[fileName]?.tags || [];
      if (!currentTags.includes(tag)) {
        return {
          ...prev,
          [fileName]: {
            ...prev[fileName],
            tags: [...currentTags, tag]
          }
        };
      }
      return prev;
    });
  };

  // Function to remove a tag from a file in upload modal
  const removeFileTag = (fileName: string, tagToRemove: string) => {
    setUploadMetadata(prev => ({
      ...prev,
      [fileName]: {
        ...prev[fileName],
        tags: prev[fileName]?.tags?.filter(tag => tag !== tagToRemove) || []
      }
    }));
  };

  // Function to start the upload process
  const startUploadProcess = async () => {
    for (const file of uploadFiles) {
      const metadata = uploadMetadata[file.name];
      if (!metadata) continue;
      
      // Create a modified file with the new name if it was changed
      let uploadFile = file;
      if (metadata.name !== file.name) {
        // Create a new file with the updated name
        uploadFile = new File([file], metadata.name, { type: file.type });
      }
      
      // Get current active folder at the time of upload
      const targetFolderId = metadata.folderId;
      
      // Add to the appropriate folder
      setFolders(prev => 
        prev.map(folder => 
          folder.id === targetFolderId 
            ? { 
                ...folder, 
                items: [
                  ...folder.items, 
                  {
                    id: `upload-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
                    name: metadata.name,
                    type: getFileType(file.type),
                    size: formatFileSize(file.size),
                    uploadDate: new Date().toISOString().split('T')[0],
                    linkedPaywalls: 0,
                    thumbnail: getFileType(file.type),
                    folderId: targetFolderId,
                    tags: metadata.tags || [],
                    isProtected: false,
                    permissions: ['read'],
                    revenue: 0
                  }
                ],
                updatedAt: new Date().toISOString()
              } 
            : folder
        )
      );
      
      // Simulate upload progress
      const uploadId = `upload-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
      setUploadProgress(prev => [
        ...prev,
        {
          id: uploadId,
          fileName: metadata.name,
          progress: 0,
          status: 'uploading',
          type: getFileType(uploadFile.type)
        }
      ]);

      // Simulate upload progress
      const interval = setInterval(() => {
        setUploadProgress(prev => 
          prev.map(upload => {
            if (upload.id === uploadId && upload.status === 'uploading') {
              const newProgress = Math.min(upload.progress + 10, 95);
              return { ...upload, progress: newProgress };
            }
            return upload;
          })
        );
      }, 200);

      // Complete the upload after a delay
      setTimeout(() => {
        clearInterval(interval);
        setUploadProgress(prev => 
          prev.map(upload => 
            upload.id === uploadId 
              ? { ...upload, progress: 100, status: 'completed' } 
              : upload
          )
        );
        
        // Clear the upload after a delay
        setTimeout(() => {
          setUploadProgress(prev => prev.filter(upload => upload.id !== uploadId));
        }, 2000);
      }, 3000); // Simulate 3 seconds upload time
    }
    
    // Close the modal and reset state
    setShowUploadModal(false);
    setUploadFiles([]);
    setUploadMetadata({});
  };

  // Function to cancel upload modal
  const cancelUpload = () => {
    setShowUploadModal(false);
    setUploadFiles([]);
    setUploadMetadata({});
  };

  // Function to toggle content selection
  const toggleContentSelection = (itemId: string) => {
    setSelectedContent(prev => {
      if (prev.includes(itemId)) {
        return prev.filter(id => id !== itemId);
      } else {
        return [...prev, itemId];
      }
    });
  };

  // Function to select all visible items
  const selectAllVisibleItems = () => {
    const visibleItems = getFilteredItems();
    setSelectedContent(visibleItems.map(item => item.id));
  };

  // Function to clear all selections
  const clearAllSelections = () => {
    setSelectedContent([]);
  };

  // Function to confirm selections and call back
  const confirmSelections = () => {
    if (onSelectCallback) {
      const selectedItems = getFilteredItems().filter(item => selectedContent.includes(item.id));
      onSelectCallback(selectedItems);
      exitSelectionMode();
    }
  };

  // Function to enter selection mode
  const enterSelectionMode = (onSelect: (selected: ContentItem[]) => void) => {
    setSelectionMode(true);
    setSelectedContent([]);
    setOnSelectCallback(() => onSelect);
  };

  // Function to exit selection mode
  const exitSelectionMode = () => {
    setSelectionMode(false);
    setSelectedContent([]);
    setOnSelectCallback(null);
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <Header
        title="Content Library"
        subtitle="Organize and manage all your digital assets"
      />
      <main>
        <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
            {/* Left Sidebar - Folder Structure */}
            <div className="lg:col-span-1">
              <div className="bg-white shadow rounded-lg p-4 dark:bg-gray-800 dark:shadow-gray-900/50">
                <div className="flex justify-between items-center mb-4">
                  <h3 className="text-lg font-medium text-gray-900 dark:text-white">Folders</h3>
                  <button 
                    onClick={() => {
                      setShowNewFolderInput(true);
                      setTimeout(() => newFolderInputRef.current?.focus(), 100);
                    }}
                    className="text-indigo-600 hover:text-indigo-900 dark:text-indigo-400 dark:hover:text-indigo-300"
                  >
                    <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                    </svg>
                  </button>
                </div>
                
                {/* New Folder Input */}
                {showNewFolderInput && (
                  <div className="mb-3 flex items-center space-x-2">
                    <input
                      ref={newFolderInputRef}
                      type="text"
                      value={newFolderName}
                      onChange={(e) => setNewFolderName(e.target.value)}
                      onKeyDown={(e) => {
                        if (e.key === 'Enter') createNewFolder();
                        if (e.key === 'Escape') {
                          setShowNewFolderInput(false);
                          setNewFolderName('');
                        }
                      }}
                      className="flex-1 block w-full border border-gray-300 rounded-md shadow-sm py-1 px-2 text-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                      placeholder="Folder name"
                    />
                    <button
                      onClick={createNewFolder}
                      className="text-green-600 hover:text-green-900 dark:text-green-400 dark:hover:text-green-300"
                    >
                      <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" />
                      </svg>
                    </button>
                    <button
                      onClick={() => {
                        setShowNewFolderInput(false);
                        setNewFolderName('');
                      }}
                      className="text-red-600 hover:text-red-900 dark:text-red-400 dark:hover:text-red-300"
                    >
                      <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                      </svg>
                    </button>
                  </div>
                )}
                
                <ul className="space-y-2">
                  {folders.map(folder => (
                    <li key={folder.id}>
                      {editingFolderId === folder.id ? (
                        <div className="flex items-center space-x-2 p-2">
                          <input
                            type="text"
                            value={editingFolderName}
                            onChange={(e) => setEditingFolderName(e.target.value)}
                            onKeyDown={(e) => {
                              if (e.key === 'Enter') saveFolderEdit();
                              if (e.key === 'Escape') {
                                setEditingFolderId(null);
                                setEditingFolderName('');
                              }
                            }}
                            className="flex-1 block w-full border border-gray-300 rounded-md shadow-sm py-1 px-2 text-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                            autoFocus
                          />
                          <button
                            onClick={saveFolderEdit}
                            className="text-green-600 hover:text-green-900 dark:text-green-400 dark:hover:text-green-300"
                          >
                            <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" />
                            </svg>
                          </button>
                          <button
                            onClick={() => {
                              setEditingFolderId(null);
                              setEditingFolderName('');
                            }}
                            className="text-red-600 hover:text-red-900 dark:text-red-400 dark:hover:text-red-300"
                          >
                            <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                            </svg>
                          </button>
                        </div>
                      ) : (
                        <div className="group relative">
                          <button
                            onClick={() => setActiveFolder(folder.id)}
                            className={`w-full flex items-center px-3 py-2 text-left rounded-md text-sm ${
                              activeFolder === folder.id
                                ? 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-200'
                                : 'text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-700'
                            }`}
                          >
                            {getFolderIcon()}
                            <span className="ml-2">{folder.name}</span>
                            <span className="ml-auto bg-gray-200 text-gray-700 text-xs px-2 py-0.5 rounded-full dark:bg-gray-700 dark:text-gray-200">
                              {folder.items.length}
                            </span>
                          </button>
                          
                          {/* Folder Actions */}
                          <div className="absolute right-2 top-1/2 transform -translate-y-1/2 opacity-0 group-hover:opacity-100 transition-opacity flex space-x-1">
                            <button
                              onClick={() => startEditingFolder(folder.id, folder.name)}
                              className="p-1 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
                            >
                              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                              </svg>
                            </button>
                            {folder.id !== '1' && ( // Don't allow deleting General folder
                              <button
                                onClick={() => deleteFolder(folder.id)}
                                className="p-1 text-gray-500 hover:text-red-600 dark:text-gray-400 dark:hover:text-red-400"
                              >
                                <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                </svg>
                              </button>
                            )}
                          </div>
                        </div>
                      )}
                    </li>
                  ))}
                </ul>
              </div>
              
              {/* Tags Section */}
              <div className="bg-white shadow rounded-lg p-4 mt-6 dark:bg-gray-800 dark:shadow-gray-900/50">
                <div className="flex justify-between items-center mb-4">
                  <h3 className="text-lg font-medium text-gray-900 dark:text-white">Tags</h3>
                  <button 
                    onClick={() => {
                      setShowAddTagInput(true);
                    }}
                    className="text-indigo-600 hover:text-indigo-900 dark:text-indigo-400 dark:hover:text-indigo-300"
                  >
                    <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                    </svg>
                  </button>
                </div>
                
                {/* Add Tag Input */}
                {showAddTagInput && (
                  <div className="mb-3 flex items-center space-x-2">
                    <input
                      type="text"
                      value={newTagName}
                      onChange={(e) => setNewTagName(e.target.value)}
                      onKeyDown={(e) => {
                        if (e.key === 'Enter') addNewTag();
                        if (e.key === 'Escape') {
                          setShowAddTagInput(false);
                          setNewTagName('');
                        }
                      }}
                      className="flex-1 block w-full border border-gray-300 rounded-md shadow-sm py-1 px-2 text-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                      placeholder="Tag name"
                      autoFocus
                    />
                    <button
                      onClick={addNewTag}
                      className="text-green-600 hover:text-green-900 dark:text-green-400 dark:hover:text-green-300"
                    >
                      <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" />
                      </svg>
                    </button>
                    <button
                      onClick={() => {
                        setShowAddTagInput(false);
                        setNewTagName('');
                      }}
                      className="text-red-600 hover:text-red-900 dark:text-red-400 dark:hover:text-red-300"
                    >
                      <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                      </svg>
                    </button>
                  </div>
                )}
                
                <div className="flex flex-wrap gap-2">
                  {tags.map(tag => (
                    <span 
                      key={tag.id} 
                      className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${tag.color}`}
                    >
                      {tag.name}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* Main Content Area */}
            <div className="lg:col-span-3">
              {/* Header with search and filters */}
              <div className="bg-white shadow rounded-lg p-4 mb-6 dark:bg-gray-800 dark:shadow-gray-900/50">
                <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                  <div className="flex-1">
                    <div className="relative rounded-md shadow-sm">
                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <svg className="h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                        </svg>
                      </div>
                      <input
                        type="text"
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                        className="block w-full pl-10 pr-12 border border-gray-300 rounded-md py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                        placeholder="Search content..."
                      />
                    </div>
                  </div>
                  
                  <div className="flex flex-wrap gap-2 items-center">
                    <select
                      value={filterType}
                      onChange={(e) => setFilterType(e.target.value)}
                      className="block border border-gray-300 rounded-md py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                    >
                      <option value="all">All Types</option>
                      <option value="document">Documents</option>
                      <option value="video">Videos</option>
                      <option value="audio">Audio</option>
                      <option value="image">Images</option>
                      <option value="link">Links</option>
                    </select>
                    
                    <button
                      onClick={() => setViewMode(viewMode === 'grid' ? 'list' : 'grid')}
                      className="inline-flex items-center px-3 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-600"
                    >
                      {viewMode === 'grid' ? (
                        <>
                          <svg className="h-5 w-5 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" />
                          </svg>
                          Grid
                        </>
                      ) : (
                        <>
                          <svg className="h-5 w-5 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 10h16M4 14h16M4 18h16" />
                          </svg>
                          List
                        </>
                      )}
                    </button>
                    
                    <button
                      onClick={handleUploadClick}
                      className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:bg-indigo-500 dark:hover:bg-indigo-600"
                    >
                      <svg className="-ml-1 mr-2 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                      </svg>
                      Upload Content
                    </button>
                    <input
                      ref={fileInputRef}
                      type="file"
                      className="hidden"
                      multiple
                      onChange={handleFileChange}
                    />
                  </div>
                </div>
              </div>

              {/* Storage Indicator */}
              <div className="bg-white shadow rounded-lg p-4 mb-6 dark:bg-gray-800 dark:shadow-gray-900/50">
                <div className="flex justify-between items-center">
                  <div>
                    <p className="text-sm font-medium text-gray-900 dark:text-white">Storage Usage</p>
                    <p className="text-sm text-gray-500 dark:text-gray-400">8.2 GB of 10 GB used</p>
                  </div>
                  <div className="w-1/2">
                    <div className="w-full bg-gray-200 rounded-full h-2.5 dark:bg-gray-700">
                      <div className="bg-indigo-600 h-2.5 rounded-full" style={{ width: '82%' }}></div>
                    </div>
                  </div>
                  <button className="text-sm text-indigo-600 hover:text-indigo-900 dark:text-indigo-400 dark:hover:text-indigo-300">
                    Upgrade
                  </button>
                </div>
              </div>

              {/* Selection Mode Bar - Replaces Bulk Actions Bar when in selection mode */}
              {selectionMode && (
                <div className="bg-white shadow rounded-lg p-4 mb-6 dark:bg-gray-800 dark:shadow-gray-900/50">
                  <div className="flex flex-wrap items-center justify-between gap-4">
                    <div className="flex items-center">
                      <span className="text-sm text-gray-700 dark:text-gray-300">
                        {selectedContent.length} item(s) selected
                      </span>
                      <button
                        onClick={clearAllSelections}
                        className="ml-4 text-sm text-indigo-600 hover:text-indigo-900 dark:text-indigo-400 dark:hover:text-indigo-300"
                      >
                        Clear selection
                      </button>
                      <button
                        onClick={exitSelectionMode}
                        className="ml-4 text-sm text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-300"
                      >
                        Exit selection
                      </button>
                    </div>
                    
                    <div className="flex flex-wrap gap-2">
                      <button
                        onClick={confirmSelections}
                        className="inline-flex items-center px-3 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:bg-indigo-500 dark:hover:bg-indigo-600"
                      >
                        <svg className="-ml-1 mr-2 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" />
                        </svg>
                        Confirm Selection
                      </button>
                    </div>
                  </div>
                </div>
              )}

              {/* Bulk Actions Bar - Only show when not in selection mode */}
              {!selectionMode && showBulkActions && (
                <div className="bg-white shadow rounded-lg p-4 mb-6 dark:bg-gray-800 dark:shadow-gray-900/50">
                  <div className="flex flex-wrap items-center justify-between gap-4">
                    <div className="flex items-center">
                      <span className="text-sm text-gray-700 dark:text-gray-300">
                        {selectedItems.length} item(s) selected
                      </span>
                      <button
                        onClick={deselectAllItems}
                        className="ml-4 text-sm text-indigo-600 hover:text-indigo-900 dark:text-indigo-400 dark:hover:text-indigo-300"
                      >
                        Clear selection
                      </button>
                    </div>
                    
                    <div className="flex flex-wrap gap-2">
                      <button
                        onClick={deleteSelectedItems}
                        className="inline-flex items-center px-3 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 dark:bg-red-500 dark:hover:bg-red-600"
                      >
                        <svg className="-ml-1 mr-2 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                        </svg>
                        Delete
                      </button>
                      
                      <div className="relative">
                        <select
                          onChange={(e) => {
                            if (e.target.value) {
                              moveSelectedItems(e.target.value);
                              e.target.value = ''; // Reset selection
                            }
                          }}
                          className="block border border-gray-300 rounded-md py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                        >
                          <option value="">Move to...</option>
                          {folders
                            .filter(folder => folder.id !== activeFolder)
                            .map(folder => (
                              <option key={folder.id} value={folder.id}>
                                {folder.name}
                              </option>
                            ))}
                        </select>
                      </div>
                      
                      <button className="inline-flex items-center px-3 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-600">
                        <svg className="-ml-1 mr-2 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                        </svg>
                        Copy Link
                      </button>
                      
                      <button className="inline-flex items-center px-3 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-600">
                        <svg className="-ml-1 mr-2 h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                        </svg>
                        Protect
                      </button>
                    </div>
                  </div>
                </div>
              )}

              {/* Drag and Drop Upload Area */}
              <div 
                className={`bg-white shadow rounded-lg p-8 mb-6 text-center border-2 border-dashed ${
                  isDragging ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/10' : 'border-gray-300 dark:border-gray-700'
                } dark:bg-gray-800 dark:shadow-gray-900/50`}
                onDragOver={handleDragOver}
                onDragLeave={handleDragLeave}
                onDrop={handleDrop}
              >
                <svg className="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
                </svg>
                <h3 className="mt-2 text-sm font-medium text-gray-900 dark:text-white">Drag and drop files</h3>
                <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  or
                </p>
                <button
                  onClick={handleUploadClick}
                  className="mt-2 inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-600"
                >
                  Browse Files
                </button>
                <input
                  ref={fileInputRef}
                  type="file"
                  className="hidden"
                  multiple
                  onChange={handleFileChange}
                />
              </div>

              {/* Upload Progress Indicators */}
              {uploadProgress.length > 0 && (
                <div className="bg-white shadow rounded-lg p-4 mb-6 dark:bg-gray-800 dark:shadow-gray-900/50">
                  <h3 className="text-sm font-medium text-gray-900 mb-3 dark:text-white">Upload Progress</h3>
                  <div className="space-y-3">
                    {uploadProgress.map(upload => (
                      <div key={upload.id} className="flex items-center">
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-medium text-gray-900 truncate dark:text-white">
                            {upload.fileName}
                          </p>
                          <div className="flex items-center mt-1">
                            <div className="w-full bg-gray-200 rounded-full h-2 dark:bg-gray-700">
                              <div
                                className={`h-2 rounded-full ${
                                  upload.status === 'completed' 
                                    ? 'bg-green-500' 
                                    : upload.status === 'failed'
                                      ? 'bg-red-500'
                                      : 'bg-indigo-600'
                                }`}
                                style={{ width: `${upload.progress}%` }}
                              ></div>
                            </div>
                            <span className="ml-3 text-sm text-gray-500 dark:text-gray-400">
                              {upload.progress}%
                            </span>
                          </div>
                        </div>
                        <div className="ml-4 flex-shrink-0">
                          {upload.status === 'completed' ? (
                            <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300">
                              Complete
                            </span>
                          ) : upload.status === 'failed' ? (
                            <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300">
                              Failed
                            </span>
                          ) : (
                            <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300">
                              Uploading
                            </span>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Content Grid/List */}
              <div className="bg-white shadow rounded-lg dark:bg-gray-800 dark:shadow-gray-900/50">
                {viewMode === 'grid' ? (
                  <div className="p-4">
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                      {getFilteredItems().map(item => (
                        <div 
                          key={item.id} 
                          className={`border rounded-lg p-4 hover:shadow-md transition-shadow duration-200 dark:border-gray-700 ${
                            selectedContent.includes(item.id) 
                              ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/20 dark:border-indigo-500' 
                              : 'border-gray-200 dark:border-gray-700 dark:bg-gray-700/50'
                          }`}
                        >
                          {/* Selection checkbox */}
                          {selectionMode && (
                            <div className="absolute top-2 left-2">
                              <input
                                type="checkbox"
                                checked={selectedContent.includes(item.id)}
                                onChange={() => toggleContentSelection(item.id)}
                                className="h-4 w-4 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500 dark:bg-gray-800 dark:border-gray-600"
                              />
                            </div>
                          )}
                          
                          <div className="flex justify-center mb-3 pt-2"> {/* Added pt-2 to account for checkbox */}
                            {getFileIcon(item.type)}
                          </div>
                          <h3 className="text-sm font-medium text-gray-900 truncate dark:text-white">
                            {item.name}
                          </h3>
                          <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                            {item.type.charAt(0).toUpperCase() + item.type.slice(1)} • {item.size}
                          </p>
                          <div className="mt-3 space-y-2">
                            <div className="flex justify-between text-xs">
                              <span className="text-gray-500 dark:text-gray-400">Paywalls:</span>
                              <span className="font-medium text-gray-900 dark:text-white">{item.linkedPaywalls}</span>
                            </div>
                            <div className="flex justify-between text-xs">
                              <span className="text-gray-500 dark:text-gray-400">Revenue:</span>
                              <span className="font-medium text-green-600 dark:text-green-400">${item.revenue?.toFixed(2) || '0.00'}</span>
                            </div>
                            <div className="flex justify-between text-xs">
                              <span className="text-gray-500 dark:text-gray-400">Date:</span>
                              <span className="font-medium text-gray-900 dark:text-white">{item.uploadDate}</span>
                            </div>
                          </div>
                          
                          {/* Tags display and input */}
                          <div className="mt-2">
                            <div className="flex flex-wrap gap-1 mb-1">
                              {item.tags.map((tag, index) => (
                                <span 
                                  key={index} 
                                  className="inline-flex items-center px-1.5 py-0.5 rounded text-xs font-medium bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-300"
                                >
                                  {tag}
                                  <button
                                    onClick={() => removeItemTag(item.id, tag)}
                                    className="ml-1 text-indigo-500 hover:text-indigo-700 dark:text-indigo-400 dark:hover:text-indigo-200"
                                  >
                                    <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                                    </svg>
                                  </button>
                                </span>
                              ))}
                            </div>
                            
                            {/* Add tag input */}
                            {!selectionMode && ( // Hide tag input when in selection mode to keep UI clean
                              <>
                                {showItemTagsInput === item.id ? (
                                  <div className="flex items-center space-x-1">
                                    <input
                                      type="text"
                                      value={editingItemTags[item.id] || ''}
                                      onChange={(e) => setEditingItemTags(prev => ({
                                        ...prev,
                                        [item.id]: e.target.value
                                      }))}
                                      onKeyDown={(e) => {
                                        if (e.key === 'Enter') {
                                          addItemTag(item.id);
                                        }
                                        if (e.key === 'Escape') {
                                          setShowItemTagsInput(null);
                                        }
                                      }}
                                      className="flex-1 block border border-gray-300 rounded text-xs py-0.5 px-1 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                                      placeholder="Add tag..."
                                      autoFocus
                                    />
                                    <button
                                      onClick={() => addItemTag(item.id)}
                                      className="text-green-600 hover:text-green-900 dark:text-green-400 dark:hover:text-green-300"
                                    >
                                      <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" />
                                      </svg>
                                    </button>
                                    <button
                                      onClick={() => setShowItemTagsInput(null)}
                                      className="text-red-600 hover:text-red-900 dark:text-red-400 dark:hover:text-red-300"
                                    >
                                      <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                                      </svg>
                                    </button>
                                  </div>
                                ) : (
                                  <button
                                    onClick={() => {
                                      setShowItemTagsInput(item.id);
                                      setEditingItemTags(prev => ({
                                        ...prev,
                                        [item.id]: ''
                                      }));
                                    }}
                                    className="text-xs text-indigo-600 hover:text-indigo-800 dark:text-indigo-400 dark:hover:text-indigo-300"
                                  >
                                    + Add tag
                                  </button>
                                )}
                              </>
                            )}
                          </div>
                          
                          {!selectionMode && (
                            <div className="flex justify-center space-x-2 mt-3">
                              <button 
                                onClick={() => handlePreview(item)}
                                className="text-indigo-600 hover:text-indigo-900 dark:text-indigo-400 dark:hover:text-indigo-300"
                                title="Preview"
                              >
                                <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                </svg>
                              </button>
                              <button 
                                onClick={() => startEditingItem(item)}
                                className="text-indigo-600 hover:text-indigo-900 dark:text-indigo-400 dark:hover:text-indigo-300"
                                title="Edit"
                              >
                                <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                </svg>
                              </button>
                              <button 
                                onClick={() => deleteItem(item.id)}
                                className="text-red-600 hover:text-red-900 dark:text-red-400 dark:hover:text-red-300"
                                title="Delete"
                              >
                                <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                </svg>
                              </button>
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                ) : (
                  <div className="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg dark:ring-gray-700">
                    <table className="min-w-full divide-y divide-gray-300 dark:divide-gray-700">
                      <thead className="bg-gray-50 dark:bg-gray-700">
                        <tr>
                          <th scope="col" className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 dark:text-white">Name</th>
                          <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 dark:text-white">Type</th>
                          <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 dark:text-white">Size</th>
                          <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 dark:text-white">Paywalls</th>
                          <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 dark:text-white">Revenue</th>
                          <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 dark:text-white">Tags</th>
                          <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900 dark:text-white">Date</th>
                          <th scope="col" className="relative py-3.5 pl-3 pr-4 sm:pr-6">
                            <span className="sr-only">Actions</span>
                          </th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-200 bg-white dark:bg-gray-800 dark:divide-gray-700">
                        {getFilteredItems().map(item => (
                          <tr key={item.id}>
                            <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 dark:text-white">
                              <div className="flex items-center">
                                <div className="flex-shrink-0 h-10 w-10">
                                  {getFileIcon(item.type)}
                                </div>
                                <div className="ml-4">
                                  <div className="text-gray-900 dark:text-white">{item.name}</div>
                                  <div className="text-gray-500 dark:text-gray-400">Folder: {folders.find(f => f.id === item.folderId)?.name}</div>
                                </div>
                              </div>
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500 dark:text-gray-400">
                              {item.type.charAt(0).toUpperCase() + item.type.slice(1)}
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500 dark:text-gray-400">
                              {item.size}
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500 dark:text-gray-400">
                              <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-300">
                                {item.linkedPaywalls} paywalls
                              </span>
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm font-medium text-green-600 dark:text-green-400">
                              ${item.revenue?.toFixed(2) || '0.00'}
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500 dark:text-gray-400">
                              <div className="flex flex-wrap gap-1">
                                {item.tags.map((tag, index) => (
                                  <span 
                                    key={index} 
                                    className="inline-flex items-center px-1.5 py-0.5 rounded text-xs font-medium bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-300"
                                  >
                                    {tag}
                                    <button
                                      onClick={() => removeItemTag(item.id, tag)}
                                      className="ml-1 text-indigo-500 hover:text-indigo-700 dark:text-indigo-400 dark:hover:text-indigo-200"
                                    >
                                      <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                                      </svg>
                                    </button>
                                  </span>
                                ))}
                                <button
                                  onClick={() => {
                                    setShowItemTagsInput(item.id);
                                    setEditingItemTags(prev => ({
                                      ...prev,
                                      [item.id]: ''
                                    }));
                                  }}
                                  className="text-xs text-indigo-600 hover:text-indigo-800 dark:text-indigo-400 dark:hover:text-indigo-300"
                                >
                                  + Add
                                </button>
                              </div>
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500 dark:text-gray-400">
                              {item.uploadDate}
                            </td>
                            <td className="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                              <div className="flex items-center justify-end space-x-2">
                                <button 
                                  onClick={() => handlePreview(item)}
                                  className="text-indigo-600 hover:text-indigo-900 dark:text-indigo-400 dark:hover:text-indigo-300"
                                >
                                  <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                  </svg>
                                </button>
                                <button 
                                  onClick={() => startEditingItem(item)}
                                  className="text-indigo-600 hover:text-indigo-900 dark:text-indigo-400 dark:hover:text-indigo-300"
                                >
                                  <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                  </svg>
                                </button>
                                <button 
                                  onClick={() => deleteItem(item.id)}
                                  className="text-red-600 hover:text-red-900 dark:text-red-400 dark:hover:text-red-300"
                                >
                                  <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                  </svg>
                                </button>
                              </div>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Preview Modal */}
        {showPreview && previewItem && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-lg shadow-xl max-w-4xl w-full max-h-[90vh] overflow-y-auto dark:bg-gray-800">
              <div className="px-6 py-4 border-b border-gray-200 dark:border-gray-700">
                <div className="flex justify-between items-center">
                  <h3 className="text-lg font-medium text-gray-900 dark:text-white">
                    {previewItem.name}
                  </h3>
                  <button
                    onClick={() => setShowPreview(false)}
                    className="text-gray-400 hover:text-gray-500 dark:text-gray-400 dark:hover:text-gray-300"
                  >
                    <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </button>
                </div>
              </div>
              <div className="p-6">
                <ContentPreview
                  file={null}
                  url=""
                  type={previewItem.type}
                />
                <div className="mt-6 grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <h4 className="text-sm font-medium text-gray-900 dark:text-white">Details</h4>
                    <dl className="mt-2 space-y-2">
                      <div className="flex justify-between">
                        <dt className="text-sm text-gray-500 dark:text-gray-400">Type</dt>
                        <dd className="text-sm text-gray-900 dark:text-white">
                          {previewItem.type.charAt(0).toUpperCase() + previewItem.type.slice(1)}
                        </dd>
                      </div>
                      <div className="flex justify-between">
                        <dt className="text-sm text-gray-500 dark:text-gray-400">Size</dt>
                        <dd className="text-sm text-gray-900 dark:text-white">
                          {previewItem.size}
                        </dd>
                      </div>
                      <div className="flex justify-between">
                        <dt className="text-sm text-gray-500 dark:text-gray-400">Upload Date</dt>
                        <dd className="text-sm text-gray-900 dark:text-white">
                          {previewItem.uploadDate}
                        </dd>
                      </div>
                      <div className="flex justify-between">
                        <dt className="text-sm text-gray-500 dark:text-gray-400">Revenue</dt>
                        <dd className="text-sm font-medium text-green-600 dark:text-green-400">
                          ${previewItem.revenue?.toFixed(2) || '0.00'}
                        </dd>
                      </div>
                    </dl>
                  </div>
                  <div>
                    <h4 className="text-sm font-medium text-gray-900 dark:text-white">Usage</h4>
                    <div className="mt-2 space-y-2">
                      <div className="flex items-center">
                        <span className="text-sm text-gray-500 dark:text-gray-400">Used in</span>
                        <span className="ml-2 inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-300">
                          {previewItem.linkedPaywalls} paywalls
                        </span>
                      </div>
                      <div className="flex items-center">
                        <span className="text-sm text-gray-500 dark:text-gray-400">Revenue</span>
                        <span className="ml-2 inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300">
                          ${previewItem.revenue?.toFixed(2) || '0.00'}
                        </span>
                      </div>
                    </div>
                  </div>
                  <div>
                    <h4 className="text-sm font-medium text-gray-900 dark:text-white">Tags</h4>
                    <div className="mt-2">
                      <div className="flex flex-wrap gap-1 mb-2">
                        {previewItem.tags.map((tag, index) => (
                          <span 
                            key={index} 
                            className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-300"
                          >
                            {tag}
                            <button
                              onClick={() => removeItemTag(previewItem.id, tag)}
                              className="ml-1 text-indigo-500 hover:text-indigo-700 dark:text-indigo-400 dark:hover:text-indigo-200"
                            >
                              <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                              </svg>
                            </button>
                          </span>
                        ))}
                      </div>
                      <div className="flex items-center space-x-1">
                        {showItemTagsInput === previewItem.id ? (
                          <>
                            <input
                              type="text"
                              value={editingItemTags[previewItem.id] || ''}
                              onChange={(e) => setEditingItemTags(prev => ({
                                ...prev,
                                [previewItem.id]: e.target.value
                              }))}
                              onKeyDown={(e) => {
                                if (e.key === 'Enter') {
                                  addItemTag(previewItem.id);
                                }
                                if (e.key === 'Escape') {
                                  setShowItemTagsInput(null);
                                }
                              }}
                              className="flex-1 block border border-gray-300 rounded text-xs py-0.5 px-1 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                              placeholder="Add tag..."
                              autoFocus
                            />
                            <button
                              onClick={() => addItemTag(previewItem.id)}
                              className="text-green-600 hover:text-green-900 dark:text-green-400 dark:hover:text-green-300"
                            >
                              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" />
                              </svg>
                            </button>
                            <button
                              onClick={() => setShowItemTagsInput(null)}
                              className="text-red-600 hover:text-red-900 dark:text-red-400 dark:hover:text-red-300"
                            >
                              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                              </svg>
                            </button>
                          </>
                        ) : (
                          <button
                            onClick={() => {
                              setShowItemTagsInput(previewItem.id);
                              setEditingItemTags(prev => ({
                                ...prev,
                                [previewItem.id]: ''
                              }));
                            }}
                            className="text-xs text-indigo-600 hover:text-indigo-800 dark:text-indigo-400 dark:hover:text-indigo-300"
                          >
                            + Add tag
                          </button>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="px-6 py-4 bg-gray-50 border-t border-gray-200 dark:bg-gray-700 dark:border-gray-600">
                <div className="flex justify-end space-x-3">
                  <button
                    onClick={() => setShowPreview(false)}
                    className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:bg-gray-600 dark:border-gray-500 dark:text-white dark:hover:bg-gray-500"
                  >
                    Close
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Edit Item Modal */}
        {editingItem && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-lg shadow-xl max-w-md w-full dark:bg-gray-800">
              <div className="px-6 py-4 border-b border-gray-200 dark:border-gray-700">
                <h3 className="text-lg font-medium text-gray-900 dark:text-white">
                  Edit Content
                </h3>
              </div>
              <div className="p-6">
                <div className="mb-4">
                  <label htmlFor="itemName" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                    Name
                  </label>
                  <input
                    type="text"
                    id="itemName"
                    value={editedItemName}
                    onChange={(e) => setEditedItemName(e.target.value)}
                    className="block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                    placeholder="Enter content name"
                  />
                </div>
              </div>
              <div className="px-6 py-4 bg-gray-50 border-t border-gray-200 dark:bg-gray-700 dark:border-gray-600">
                <div className="flex justify-end space-x-3">
                  <button
                    onClick={cancelItemEdit}
                    className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:bg-gray-600 dark:border-gray-500 dark:text-white dark:hover:bg-gray-500"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={saveItemEdit}
                    className="px-4 py-2 text-sm font-medium text-white bg-indigo-600 border border-transparent rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:bg-indigo-500 dark:hover:bg-indigo-600"
                  >
                    Save Changes
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Upload Modal */}
        {showUploadModal && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-lg shadow-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto dark:bg-gray-800">
              <div className="px-6 py-4 border-b border-gray-200 dark:border-gray-700">
                <h3 className="text-lg font-medium text-gray-900 dark:text-white">
                  Upload Content
                </h3>
                <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  Configure your files before uploading
                </p>
              </div>
              <div className="p-6">
                {uploadFiles.map((file, index) => {
                  const metadata = uploadMetadata[file.name];
                  if (!metadata) return null;
                  
                  return (
                    <div key={index} className="mb-6 p-4 border border-gray-200 rounded-lg dark:border-gray-700">
                      <h4 className="text-md font-medium text-gray-900 dark:text-white mb-3">
                        {file.name} ({formatFileSize(file.size)})
                      </h4>
                      
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        {/* Name field */}
                        <div>
                          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                            Name
                          </label>
                          <input
                            type="text"
                            value={metadata.name}
                            onChange={(e) => updateFileMetadata(file.name, 'name', e.target.value)}
                            className="block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                            placeholder="File name"
                          />
                        </div>
                        
                        {/* Folder selection */}
                        <div>
                          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                            Folder
                          </label>
                          <select
                            value={metadata.folderId}
                            onChange={(e) => updateFileMetadata(file.name, 'folderId', e.target.value)}
                            className="block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                          >
                            {folders.map(folder => (
                              <option key={folder.id} value={folder.id}>
                                {folder.name}
                              </option>
                            ))}
                          </select>
                        </div>
                        
                        {/* Tags */}
                        <div className="md:col-span-2">
                          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                            Tags
                          </label>
                          <div className="flex flex-wrap gap-2 mb-2">
                            {metadata.tags.map((tag, tagIndex) => (
                              <span 
                                key={tagIndex} 
                                className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-300"
                              >
                                {tag}
                                <button
                                  onClick={() => removeFileTag(file.name, tag)}
                                  className="ml-1 text-indigo-500 hover:text-indigo-700 dark:text-indigo-400 dark:hover:text-indigo-200"
                                >
                                  <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                                  </svg>
                                </button>
                              </span>
                            ))}
                          </div>
                          <div className="flex">
                            <input
                              type="text"
                              placeholder="Add a tag..."
                              className="flex-1 border border-gray-300 rounded-l-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                              onKeyDown={(e) => {
                                if (e.key === 'Enter') {
                                  e.preventDefault();
                                  const target = e.target as HTMLInputElement;
                                  if (target.value.trim()) {
                                    addFileTag(file.name, target.value.trim());
                                    target.value = '';
                                  }
                                }
                              }}
                            />
                            <button
                              onClick={(e) => {
                                e.preventDefault();
                                const input = (e.target as HTMLElement).previousElementSibling as HTMLInputElement;
                                if (input.value.trim()) {
                                  addFileTag(file.name, input.value.trim());
                                  input.value = '';
                                }
                              }}
                              className="inline-flex items-center px-3 py-2 border border-l-0 border-gray-300 rounded-r-md bg-gray-50 text-sm font-medium text-gray-700 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:bg-gray-700 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-600"
                            >
                              Add
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
              <div className="px-6 py-4 bg-gray-50 border-t border-gray-200 dark:bg-gray-700 dark:border-gray-600">
                <div className="flex justify-end space-x-3">
                  <button
                    onClick={cancelUpload}
                    className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:bg-gray-600 dark:border-gray-500 dark:text-white dark:hover:bg-gray-500"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={startUploadProcess}
                    className="px-4 py-2 text-sm font-medium text-white bg-indigo-600 border border-transparent rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:bg-indigo-500 dark:hover:bg-indigo-600"
                  >
                    Start Upload
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
};

export default ContentLibrary;