"""Add token blacklist table

Revision ID: 8658389bca8a
Revises: e494783dd884
Create Date: 2025-10-29 06:56:27.596896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8658389bca8a'
down_revision = 'e494783dd884'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###