"""Add payment methods table

Revision ID: e494783dd884
Revises: 20251023150000
Create Date: 2025-10-29 06:43:17.455372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e494783dd884'
down_revision = '20251023150000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_preferences_created_at', table_name='notification_preferences')
    op.drop_index('ix_notification_preferences_id', table_name='notification_preferences')
    op.drop_index('ix_notification_preferences_user_id', table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index('ix_affiliates_affiliate_code', table_name='affiliates')
    op.drop_index('ix_affiliates_created_at', table_name='affiliates')
    op.drop_index('ix_affiliates_id', table_name='affiliates')
    op.drop_index('ix_affiliates_is_active', table_name='affiliates')
    op.drop_index('ix_affiliates_user_id', table_name='affiliates')
    op.drop_table('affiliates')
    op.drop_index('ix_email_lists_created_at', table_name='email_lists')
    op.drop_index('ix_email_lists_id', table_name='email_lists')
    op.drop_index('ix_email_lists_is_active', table_name='email_lists')
    op.drop_table('email_lists')
    op.drop_index('ix_users_country', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_users_currency', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_is_verified', table_name='users')
    op.drop_index('ix_users_last_login', table_name='users')
    op.drop_index('ix_users_mfa_enabled', table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_user_type', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_subscriptions_created_at', table_name='subscriptions')
    op.drop_index('ix_subscriptions_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_plan_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_status', table_name='subscriptions')
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_coupons_code', table_name='coupons')
    op.drop_index('ix_coupons_created_at', table_name='coupons')
    op.drop_index('ix_coupons_id', table_name='coupons')
    op.drop_index('ix_coupons_is_active', table_name='coupons')
    op.drop_table('coupons')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_notification_type', table_name='notifications')
    op.drop_index('ix_notifications_priority', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_paywalls_conversions', table_name='paywalls')
    op.drop_index('ix_paywalls_created_at', table_name='paywalls')
    op.drop_index('ix_paywalls_currency', table_name='paywalls')
    op.drop_index('ix_paywalls_description', table_name='paywalls')
    op.drop_index('ix_paywalls_duration', table_name='paywalls')
    op.drop_index('ix_paywalls_id', table_name='paywalls')
    op.drop_index('ix_paywalls_owner_id', table_name='paywalls')
    op.drop_index('ix_paywalls_price', table_name='paywalls')
    op.drop_index('ix_paywalls_status', table_name='paywalls')
    op.drop_index('ix_paywalls_title', table_name='paywalls')
    op.drop_index('ix_paywalls_views', table_name='paywalls')
    op.drop_table('paywalls')
    op.drop_index('ix_subscription_plans_created_at', table_name='subscription_plans')
    op.drop_index('ix_subscription_plans_currency', table_name='subscription_plans')
    op.drop_index('ix_subscription_plans_id', table_name='subscription_plans')
    op.drop_index('ix_subscription_plans_is_active', table_name='subscription_plans')
    op.drop_index('ix_subscription_plans_name', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index('ix_invoices_created_at', table_name='invoices')
    op.drop_index('ix_invoices_id', table_name='invoices')
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_subscription_id', table_name='invoices')
    op.drop_index('ix_invoices_user_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_affiliate_referrals_affiliate_id', table_name='affiliate_referrals')
    op.drop_index('ix_affiliate_referrals_commission_status', table_name='affiliate_referrals')
    op.drop_index('ix_affiliate_referrals_created_at', table_name='affiliate_referrals')
    op.drop_index('ix_affiliate_referrals_id', table_name='affiliate_referrals')
    op.drop_index('ix_affiliate_referrals_order_id', table_name='affiliate_referrals')
    op.drop_index('ix_affiliate_referrals_referral_code', table_name='affiliate_referrals')
    op.drop_index('ix_affiliate_referrals_referred_user_id', table_name='affiliate_referrals')
    op.drop_table('affiliate_referrals')
    op.drop_index('ix_content_access_content_id', table_name='content_access')
    op.drop_index('ix_content_access_expires_at', table_name='content_access')
    op.drop_index('ix_content_access_granted_at', table_name='content_access')
    op.drop_index('ix_content_access_granted_by', table_name='content_access')
    op.drop_index('ix_content_access_id', table_name='content_access')
    op.drop_index('ix_content_access_is_active', table_name='content_access')
    op.drop_index('ix_content_access_user_id', table_name='content_access')
    op.drop_table('content_access')
    op.drop_index('ix_support_categories_created_at', table_name='support_categories')
    op.drop_index('ix_support_categories_id', table_name='support_categories')
    op.drop_index('ix_support_categories_is_active', table_name='support_categories')
    op.drop_index('ix_support_categories_name', table_name='support_categories')
    op.drop_table('support_categories')
    op.drop_index('ix_billing_info_created_at', table_name='billing_info')
    op.drop_index('ix_billing_info_id', table_name='billing_info')
    op.drop_index('ix_billing_info_user_id', table_name='billing_info')
    op.drop_table('billing_info')
    op.drop_index('ix_marketing_campaigns_campaign_type', table_name='marketing_campaigns')
    op.drop_index('ix_marketing_campaigns_created_at', table_name='marketing_campaigns')
    op.drop_index('ix_marketing_campaigns_id', table_name='marketing_campaigns')
    op.drop_index('ix_marketing_campaigns_status', table_name='marketing_campaigns')
    op.drop_table('marketing_campaigns')
    op.drop_index('ix_email_subscribers_created_at', table_name='email_subscribers')
    op.drop_index('ix_email_subscribers_email', table_name='email_subscribers')
    op.drop_index('ix_email_subscribers_email_list_id', table_name='email_subscribers')
    op.drop_index('ix_email_subscribers_id', table_name='email_subscribers')
    op.drop_index('ix_email_subscribers_is_subscribed', table_name='email_subscribers')
    op.drop_table('email_subscribers')
    op.drop_index('ix_content_created_at', table_name='content')
    op.drop_index('ix_content_currency', table_name='content')
    op.drop_index('ix_content_description', table_name='content')
    op.drop_index('ix_content_file_path', table_name='content')
    op.drop_index('ix_content_id', table_name='content')
    op.drop_index('ix_content_is_protected', table_name='content')
    op.drop_index('ix_content_owner_id', table_name='content')
    op.drop_index('ix_content_price', table_name='content')
    op.drop_index('ix_content_title', table_name='content')
    op.drop_index('ix_content_type', table_name='content')
    op.drop_index('ix_content_updated_at', table_name='content')
    op.drop_index('ix_content_url', table_name='content')
    op.drop_table('content')
    op.drop_index('ix_discount_codes_code', table_name='discount_codes')
    op.drop_index('ix_discount_codes_created_at', table_name='discount_codes')
    op.drop_index('ix_discount_codes_id', table_name='discount_codes')
    op.drop_index('ix_discount_codes_is_active', table_name='discount_codes')
    op.drop_table('discount_codes')
    op.drop_index('ix_payments_amount', table_name='payments')
    op.drop_index('ix_payments_channel', table_name='payments')
    op.drop_index('ix_payments_created_at', table_name='payments')
    op.drop_index('ix_payments_currency', table_name='payments')
    op.drop_index('ix_payments_customer_email', table_name='payments')
    op.drop_index('ix_payments_customer_name', table_name='payments')
    op.drop_index('ix_payments_id', table_name='payments')
    op.drop_index('ix_payments_owner_id', table_name='payments')
    op.drop_index('ix_payments_payment_method', table_name='payments')
    op.drop_index('ix_payments_paywall_id', table_name='payments')
    op.drop_index('ix_payments_reference', table_name='payments')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_support_ticket_responses_created_at', table_name='support_ticket_responses')
    op.drop_index('ix_support_ticket_responses_id', table_name='support_ticket_responses')
    op.drop_index('ix_support_ticket_responses_ticket_id', table_name='support_ticket_responses')
    op.drop_index('ix_support_ticket_responses_user_id', table_name='support_ticket_responses')
    op.drop_table('support_ticket_responses')
    op.drop_index('ix_token_blacklist_blacklisted_on', table_name='token_blacklist')
    op.drop_index('ix_token_blacklist_expires_at', table_name='token_blacklist')
    op.drop_index('ix_token_blacklist_id', table_name='token_blacklist')
    op.drop_index('ix_token_blacklist_token', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index('ix_support_tickets_assigned_to', table_name='support_tickets')
    op.drop_index('ix_support_tickets_category_id', table_name='support_tickets')
    op.drop_index('ix_support_tickets_created_at', table_name='support_tickets')
    op.drop_index('ix_support_tickets_id', table_name='support_tickets')
    op.drop_index('ix_support_tickets_priority', table_name='support_tickets')
    op.drop_index('ix_support_tickets_status', table_name='support_tickets')
    op.drop_index('ix_support_tickets_user_id', table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index('ix_customers_created_at', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_index('ix_customers_id', table_name='customers')
    op.drop_index('ix_customers_join_date', table_name='customers')
    op.drop_index('ix_customers_last_purchase', table_name='customers')
    op.drop_index('ix_customers_name', table_name='customers')
    op.drop_index('ix_customers_owner_id', table_name='customers')
    op.drop_index('ix_customers_status', table_name='customers')
    op.drop_index('ix_customers_total_purchases', table_name='customers')
    op.drop_index('ix_customers_total_spent', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('total_spent', sa.FLOAT(), nullable=True),
    sa.Column('total_purchases', sa.INTEGER(), nullable=True),
    sa.Column('last_purchase', sa.DATETIME(), nullable=True),
    sa.Column('join_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_total_spent', 'customers', ['total_spent'], unique=False)
    op.create_index('ix_customers_total_purchases', 'customers', ['total_purchases'], unique=False)
    op.create_index('ix_customers_status', 'customers', ['status'], unique=False)
    op.create_index('ix_customers_owner_id', 'customers', ['owner_id'], unique=False)
    op.create_index('ix_customers_name', 'customers', ['name'], unique=False)
    op.create_index('ix_customers_last_purchase', 'customers', ['last_purchase'], unique=False)
    op.create_index('ix_customers_join_date', 'customers', ['join_date'], unique=False)
    op.create_index('ix_customers_id', 'customers', ['id'], unique=False)
    op.create_index('ix_customers_email', 'customers', ['email'], unique=1)
    op.create_index('ix_customers_created_at', 'customers', ['created_at'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('priority', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), nullable=True),
    sa.Column('resolution', sa.TEXT(), nullable=True),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['support_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_support_tickets_user_id', 'support_tickets', ['user_id'], unique=False)
    op.create_index('ix_support_tickets_status', 'support_tickets', ['status'], unique=False)
    op.create_index('ix_support_tickets_priority', 'support_tickets', ['priority'], unique=False)
    op.create_index('ix_support_tickets_id', 'support_tickets', ['id'], unique=False)
    op.create_index('ix_support_tickets_created_at', 'support_tickets', ['created_at'], unique=False)
    op.create_index('ix_support_tickets_category_id', 'support_tickets', ['category_id'], unique=False)
    op.create_index('ix_support_tickets_assigned_to', 'support_tickets', ['assigned_to'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(), nullable=False),
    sa.Column('blacklisted_on', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_token_blacklist_token', 'token_blacklist', ['token'], unique=1)
    op.create_index('ix_token_blacklist_id', 'token_blacklist', ['id'], unique=False)
    op.create_index('ix_token_blacklist_expires_at', 'token_blacklist', ['expires_at'], unique=False)
    op.create_index('ix_token_blacklist_blacklisted_on', 'token_blacklist', ['blacklisted_on'], unique=False)
    op.create_table('support_ticket_responses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('is_internal', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_support_ticket_responses_user_id', 'support_ticket_responses', ['user_id'], unique=False)
    op.create_index('ix_support_ticket_responses_ticket_id', 'support_ticket_responses', ['ticket_id'], unique=False)
    op.create_index('ix_support_ticket_responses_id', 'support_ticket_responses', ['id'], unique=False)
    op.create_index('ix_support_ticket_responses_created_at', 'support_ticket_responses', ['created_at'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('paywall_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_email', sa.VARCHAR(), nullable=True),
    sa.Column('customer_name', sa.VARCHAR(), nullable=True),
    sa.Column('reference', sa.VARCHAR(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(), nullable=True),
    sa.Column('channel', sa.VARCHAR(), nullable=True),
    sa.Column('gateway_response', sqlite.JSON(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paywall_id'], ['paywalls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_index('ix_payments_reference', 'payments', ['reference'], unique=1)
    op.create_index('ix_payments_paywall_id', 'payments', ['paywall_id'], unique=False)
    op.create_index('ix_payments_payment_method', 'payments', ['payment_method'], unique=False)
    op.create_index('ix_payments_owner_id', 'payments', ['owner_id'], unique=False)
    op.create_index('ix_payments_id', 'payments', ['id'], unique=False)
    op.create_index('ix_payments_customer_name', 'payments', ['customer_name'], unique=False)
    op.create_index('ix_payments_customer_email', 'payments', ['customer_email'], unique=False)
    op.create_index('ix_payments_currency', 'payments', ['currency'], unique=False)
    op.create_index('ix_payments_created_at', 'payments', ['created_at'], unique=False)
    op.create_index('ix_payments_channel', 'payments', ['channel'], unique=False)
    op.create_index('ix_payments_amount', 'payments', ['amount'], unique=False)
    op.create_table('discount_codes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('discount_type', sa.VARCHAR(), nullable=True),
    sa.Column('discount_value', sa.FLOAT(), nullable=False),
    sa.Column('usage_limit', sa.INTEGER(), nullable=True),
    sa.Column('used_count', sa.INTEGER(), nullable=True),
    sa.Column('valid_from', sa.DATETIME(), nullable=False),
    sa.Column('valid_until', sa.DATETIME(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discount_codes_is_active', 'discount_codes', ['is_active'], unique=False)
    op.create_index('ix_discount_codes_id', 'discount_codes', ['id'], unique=False)
    op.create_index('ix_discount_codes_created_at', 'discount_codes', ['created_at'], unique=False)
    op.create_index('ix_discount_codes_code', 'discount_codes', ['code'], unique=1)
    op.create_table('content',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=True),
    sa.Column('is_protected', sa.BOOLEAN(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('paywall_title', sa.VARCHAR(), nullable=True),
    sa.Column('paywall_description', sa.TEXT(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_url', 'content', ['url'], unique=False)
    op.create_index('ix_content_updated_at', 'content', ['updated_at'], unique=False)
    op.create_index('ix_content_type', 'content', ['type'], unique=False)
    op.create_index('ix_content_title', 'content', ['title'], unique=False)
    op.create_index('ix_content_price', 'content', ['price'], unique=False)
    op.create_index('ix_content_owner_id', 'content', ['owner_id'], unique=False)
    op.create_index('ix_content_is_protected', 'content', ['is_protected'], unique=False)
    op.create_index('ix_content_id', 'content', ['id'], unique=False)
    op.create_index('ix_content_file_path', 'content', ['file_path'], unique=False)
    op.create_index('ix_content_description', 'content', ['description'], unique=False)
    op.create_index('ix_content_currency', 'content', ['currency'], unique=False)
    op.create_index('ix_content_created_at', 'content', ['created_at'], unique=False)
    op.create_table('email_subscribers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email_list_id', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('is_subscribed', sa.BOOLEAN(), nullable=True),
    sa.Column('is_confirmed', sa.BOOLEAN(), nullable=True),
    sa.Column('unsubscribe_reason', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['email_list_id'], ['email_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_subscribers_is_subscribed', 'email_subscribers', ['is_subscribed'], unique=False)
    op.create_index('ix_email_subscribers_id', 'email_subscribers', ['id'], unique=False)
    op.create_index('ix_email_subscribers_email_list_id', 'email_subscribers', ['email_list_id'], unique=False)
    op.create_index('ix_email_subscribers_email', 'email_subscribers', ['email'], unique=False)
    op.create_index('ix_email_subscribers_created_at', 'email_subscribers', ['created_at'], unique=False)
    op.create_table('marketing_campaigns',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('campaign_type', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('target_audience', sa.VARCHAR(), nullable=True),
    sa.Column('metrics', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_marketing_campaigns_status', 'marketing_campaigns', ['status'], unique=False)
    op.create_index('ix_marketing_campaigns_id', 'marketing_campaigns', ['id'], unique=False)
    op.create_index('ix_marketing_campaigns_created_at', 'marketing_campaigns', ['created_at'], unique=False)
    op.create_index('ix_marketing_campaigns_campaign_type', 'marketing_campaigns', ['campaign_type'], unique=False)
    op.create_table('billing_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('company', sa.VARCHAR(), nullable=True),
    sa.Column('address_line_1', sa.VARCHAR(), nullable=True),
    sa.Column('address_line_2', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('postal_code', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_billing_info_user_id', 'billing_info', ['user_id'], unique=1)
    op.create_index('ix_billing_info_id', 'billing_info', ['id'], unique=False)
    op.create_index('ix_billing_info_created_at', 'billing_info', ['created_at'], unique=False)
    op.create_table('support_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_support_categories_name', 'support_categories', ['name'], unique=1)
    op.create_index('ix_support_categories_is_active', 'support_categories', ['is_active'], unique=False)
    op.create_index('ix_support_categories_id', 'support_categories', ['id'], unique=False)
    op.create_index('ix_support_categories_created_at', 'support_categories', ['created_at'], unique=False)
    op.create_table('content_access',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('granted_by', sa.VARCHAR(), nullable=True),
    sa.Column('granted_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_access_user_id', 'content_access', ['user_id'], unique=False)
    op.create_index('ix_content_access_is_active', 'content_access', ['is_active'], unique=False)
    op.create_index('ix_content_access_id', 'content_access', ['id'], unique=False)
    op.create_index('ix_content_access_granted_by', 'content_access', ['granted_by'], unique=False)
    op.create_index('ix_content_access_granted_at', 'content_access', ['granted_at'], unique=False)
    op.create_index('ix_content_access_expires_at', 'content_access', ['expires_at'], unique=False)
    op.create_index('ix_content_access_content_id', 'content_access', ['content_id'], unique=False)
    op.create_table('affiliate_referrals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('affiliate_id', sa.INTEGER(), nullable=True),
    sa.Column('referred_user_id', sa.INTEGER(), nullable=True),
    sa.Column('referral_code', sa.VARCHAR(), nullable=True),
    sa.Column('commission_amount', sa.FLOAT(), nullable=True),
    sa.Column('commission_status', sa.VARCHAR(), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('is_paid', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_affiliate_referrals_referred_user_id', 'affiliate_referrals', ['referred_user_id'], unique=False)
    op.create_index('ix_affiliate_referrals_referral_code', 'affiliate_referrals', ['referral_code'], unique=False)
    op.create_index('ix_affiliate_referrals_order_id', 'affiliate_referrals', ['order_id'], unique=False)
    op.create_index('ix_affiliate_referrals_id', 'affiliate_referrals', ['id'], unique=False)
    op.create_index('ix_affiliate_referrals_created_at', 'affiliate_referrals', ['created_at'], unique=False)
    op.create_index('ix_affiliate_referrals_commission_status', 'affiliate_referrals', ['commission_status'], unique=False)
    op.create_index('ix_affiliate_referrals_affiliate_id', 'affiliate_referrals', ['affiliate_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('subscription_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_user_id', 'invoices', ['user_id'], unique=False)
    op.create_index('ix_invoices_subscription_id', 'invoices', ['subscription_id'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=1)
    op.create_index('ix_invoices_id', 'invoices', ['id'], unique=False)
    op.create_index('ix_invoices_created_at', 'invoices', ['created_at'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('billing_period', sa.VARCHAR(), nullable=True),
    sa.Column('features', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscription_plans_name', 'subscription_plans', ['name'], unique=False)
    op.create_index('ix_subscription_plans_is_active', 'subscription_plans', ['is_active'], unique=False)
    op.create_index('ix_subscription_plans_id', 'subscription_plans', ['id'], unique=False)
    op.create_index('ix_subscription_plans_currency', 'subscription_plans', ['currency'], unique=False)
    op.create_index('ix_subscription_plans_created_at', 'subscription_plans', ['created_at'], unique=False)
    op.create_table('paywalls',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('content_ids', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('success_redirect_url', sa.VARCHAR(), nullable=True),
    sa.Column('cancel_redirect_url', sa.VARCHAR(), nullable=True),
    sa.Column('webhook_url', sa.VARCHAR(), nullable=True),
    sa.Column('views', sa.INTEGER(), nullable=True),
    sa.Column('conversions', sa.INTEGER(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paywalls_views', 'paywalls', ['views'], unique=False)
    op.create_index('ix_paywalls_title', 'paywalls', ['title'], unique=False)
    op.create_index('ix_paywalls_status', 'paywalls', ['status'], unique=False)
    op.create_index('ix_paywalls_price', 'paywalls', ['price'], unique=False)
    op.create_index('ix_paywalls_owner_id', 'paywalls', ['owner_id'], unique=False)
    op.create_index('ix_paywalls_id', 'paywalls', ['id'], unique=False)
    op.create_index('ix_paywalls_duration', 'paywalls', ['duration'], unique=False)
    op.create_index('ix_paywalls_description', 'paywalls', ['description'], unique=False)
    op.create_index('ix_paywalls_currency', 'paywalls', ['currency'], unique=False)
    op.create_index('ix_paywalls_created_at', 'paywalls', ['created_at'], unique=False)
    op.create_index('ix_paywalls_conversions', 'paywalls', ['conversions'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('notification_type', sa.VARCHAR(), nullable=True),
    sa.Column('priority', sa.VARCHAR(), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('is_sent', sa.BOOLEAN(), nullable=True),
    sa.Column('sent_via', sa.VARCHAR(), nullable=True),
    sa.Column('data', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('read_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_priority', 'notifications', ['priority'], unique=False)
    op.create_index('ix_notifications_notification_type', 'notifications', ['notification_type'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=True),
    sa.Column('discount_type', sa.VARCHAR(), nullable=True),
    sa.Column('discount_value', sa.FLOAT(), nullable=False),
    sa.Column('usage_limit', sa.INTEGER(), nullable=True),
    sa.Column('used_count', sa.INTEGER(), nullable=True),
    sa.Column('valid_from', sa.DATETIME(), nullable=False),
    sa.Column('valid_until', sa.DATETIME(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coupons_is_active', 'coupons', ['is_active'], unique=False)
    op.create_index('ix_coupons_id', 'coupons', ['id'], unique=False)
    op.create_index('ix_coupons_created_at', 'coupons', ['created_at'], unique=False)
    op.create_index('ix_coupons_code', 'coupons', ['code'], unique=1)
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('plan_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('next_billing_date', sa.DATETIME(), nullable=True),
    sa.Column('auto_renew', sa.BOOLEAN(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('ix_subscriptions_plan_id', 'subscriptions', ['plan_id'], unique=False)
    op.create_index('ix_subscriptions_id', 'subscriptions', ['id'], unique=False)
    op.create_index('ix_subscriptions_created_at', 'subscriptions', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('mfa_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('mfa_secret', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('avatar', sa.VARCHAR(), nullable=True),
    sa.Column('user_type', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_user_type', 'users', ['user_type'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_index('ix_users_mfa_enabled', 'users', ['mfa_enabled'], unique=False)
    op.create_index('ix_users_last_login', 'users', ['last_login'], unique=False)
    op.create_index('ix_users_is_verified', 'users', ['is_verified'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_index('ix_users_currency', 'users', ['currency'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_country', 'users', ['country'], unique=False)
    op.create_table('email_lists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('subscriber_count', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_lists_is_active', 'email_lists', ['is_active'], unique=False)
    op.create_index('ix_email_lists_id', 'email_lists', ['id'], unique=False)
    op.create_index('ix_email_lists_created_at', 'email_lists', ['created_at'], unique=False)
    op.create_table('affiliates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('commission_rate', sa.FLOAT(), nullable=True),
    sa.Column('affiliate_code', sa.VARCHAR(), nullable=True),
    sa.Column('earnings', sa.FLOAT(), nullable=True),
    sa.Column('paid_earnings', sa.FLOAT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_affiliates_user_id', 'affiliates', ['user_id'], unique=1)
    op.create_index('ix_affiliates_is_active', 'affiliates', ['is_active'], unique=False)
    op.create_index('ix_affiliates_id', 'affiliates', ['id'], unique=False)
    op.create_index('ix_affiliates_created_at', 'affiliates', ['created_at'], unique=False)
    op.create_index('ix_affiliates_affiliate_code', 'affiliates', ['affiliate_code'], unique=1)
    op.create_table('notification_preferences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('email_notifications', sa.BOOLEAN(), nullable=True),
    sa.Column('push_notifications', sa.BOOLEAN(), nullable=True),
    sa.Column('in_app_notifications', sa.BOOLEAN(), nullable=True),
    sa.Column('marketing_emails', sa.BOOLEAN(), nullable=True),
    sa.Column('newsletter', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_preferences_user_id', 'notification_preferences', ['user_id'], unique=1)
    op.create_index('ix_notification_preferences_id', 'notification_preferences', ['id'], unique=False)
    op.create_index('ix_notification_preferences_created_at', 'notification_preferences', ['created_at'], unique=False)
    # ### end Alembic commands ###